---
Packaging:
  pomVersion: 1.0.3.0
  isDeveloper: false
  isDevelopment: true
  isProduction: false
  time_zone: Eastern Time (US & Canada)

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost

access_profile:
  default_unknown_to_unsecure: false
  options_keyword: options
  access_registry_filename:  # defaults to <root>/config  -- no override
    basename: access_registry
    extension: xml
  content_registry_filename:  # defaults to <root>/config  -- no override
    basename: content_registry
    extension: xml

security:
  admin_role: Services.Action.Admin
  extra_digest_strength: 3
  session_expires: 480                # 8 hours
  remembered_for: 2160                # 32 hours
  verify_login_after_seconds: 14400   # 4 hours
  ! public_pages: # not easily stored in the xml, because of leading slash
   - /assets

  ! user_options:
   - Manager
   - Developer
   - EmployeePrimary
   - EmployeeSecondary
   - BranchPrimary
   - BranchSecondary
   - VendorPrimary
   - VendorSecondary
   - '0034'
   - '0037'
   - '0040'
   - '1601'
   - '1602'
   - '0099'
