# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'support/utilities'
require 'support/test_data_serializers'

RSpec.configure do |config|

  Kernel.srand config.seed

  if config.files_to_run.one?
    config.formatter = :documentation
  else
    config.formatter = :progress
  end

  config.order = :random
  config.color = true
  config.tty = false
  config.warnings = false

  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  # TODO: Causes the Feature tag to fail in Capybara specs
  # config.disable_monkey_patching!  # -- breaks rspec runtime

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    expectations.syntax = :expect
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true # prefer true
  end

  config.include Utilities
  config.include TestDataSerializers

end
